=== David-Job/xml_colegio/colegio.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Colegio -->
  <xs:element name="colegio">
    <xs:complexType>
      <xs:sequence>

        <!-- Alumnos -->
        <xs:element name="alumnos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="alumno" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="NombreApellido" />
                    <xs:element name="apellido" type="NombreApellido" />
                    <xs:element name="curso" type="NivelEducativo" />
                    <xs:element name="nota_media" type="Nota" />
                  </xs:sequence>
                  <xs:attribute name="num_exp" type="ExpedienteAlumno" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Profesores -->
        <xs:element name="profesores">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="profesor" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="NombreApellido" />
                    <xs:element name="apellido" type="NombreApellido" />
                    <xs:element name="departamento" type="Departamento" />
                    <xs:element name="anyos_experiencia" type="Anyo" />
                  </xs:sequence>
                  <xs:attribute name="iniciales" type="Iniciales" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Asignaturas -->
        <xs:element name="asignaturas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="asignatura" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="NombreApellido" />
                    <xs:element name="nivel" type="NivelEducativo" />
                    <xs:element name="departamento" type="NombreApellido" />
                    <xs:element name="profesor" type="Iniciales" />
                  </xs:sequence>
                  <xs:attribute name="cod_asignatura" type="CodigoAsignatura" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tipos personalizados -->
  <xs:simpleType name="ExpedienteAlumno">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][0-9]{3}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CodigoAsignatura">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}[0-9]{3}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NombreApellido">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-zÁÉÍÓÚáéíóúÑñ ]+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Nota">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="10" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Anyo">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NivelEducativo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1º" />
      <xs:enumeration value="2º" />
      <xs:enumeration value="3º" />
      <xs:enumeration value="4º" />
      <xs:enumeration value="5º" />
      <xs:enumeration value="6º" />
      <xs:enumeration value="1º ESO" />
      <xs:enumeration value="2º ESO" />
      <xs:enumeration value="3º ESO" />
      <xs:enumeration value="4º ESO" />
      <xs:enumeration value="1º BACH" />
      <xs:enumeration value="2º BACH" />
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="Departamento">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ciencia y Tecnología" />
      <xs:enumeration value="Ciencias Sociales" />
      <xs:enumeration value="Humanidades" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Iniciales">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== David-Job/xml_colegio/colegio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="alumnos.xsl"?>
<colegio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="colegio.xsd">

  <alumnos>

    <alumno num_exp="A001">
      <nombre>Pablo</nombre>
      <apellido>Millas Morales</apellido>
      <curso>2º ESO</curso>
      <nota_media>7</nota_media>
    </alumno>

    <alumno num_exp="A002">
      <nombre>Jose</nombre>
      <apellido>Cruz Caballero</apellido>
      <curso>2º ESO</curso>
      <nota_media>10</nota_media>
    </alumno>

    <alumno num_exp="B003">
      <nombre>Pepe</nombre>
      <apellido>Cruz</apellido>
      <curso>2º ESO</curso>
      <nota_media>10</nota_media>
    </alumno>

    <alumno num_exp="C004">
      <nombre>David</nombre>
      <apellido>Jiménez Suárez</apellido>
      <curso>2º BACH</curso>
      <nota_media>5</nota_media>
    </alumno>

  </alumnos>


  <profesores>

    <profesor iniciales="JJJ">
      <nombre>Jose</nombre>
      <apellido>Jose Jose</apellido>
      <departamento>Ciencia y Tecnología</departamento>
      <anyos_experiencia>8</anyos_experiencia>
    </profesor>

    <profesor iniciales="ABC">
      <nombre>Alberto</nombre>
      <apellido>Bolaños Carrero</apellido>
      <departamento>Ciencia y Tecnología</departamento>
      <anyos_experiencia>20</anyos_experiencia>
    </profesor>

    <profesor iniciales="CLC">
      <nombre>Constantino</nombre>
      <apellido>Lantigua Calderín</apellido>
      <departamento>Ciencia y Tecnología</departamento>
      <anyos_experiencia>1000000000</anyos_experiencia>
    </profesor>

  </profesores>


  <asignaturas>

    <asignatura cod_asignatura="MAT001">
      <nombre>Matemáticas</nombre>
      <nivel>1º</nivel>
      <departamento>Ciencia y Tecnología</departamento>
      <profesor>JJJ</profesor>
    </asignatura>

    <asignatura cod_asignatura="MAT100">
      <nombre>Matemáticas I</nombre>
      <nivel>1º BACH</nivel>
      <departamento>Ciencia y Tecnología</departamento>
      <profesor>JJJ</profesor>
    </asignatura>

    <asignatura cod_asignatura="LIT002">
      <nombre>Lengua y Literatura</nombre>
      <nivel>2º BACH</nivel>
      <departamento>Humanidades</departamento>
      <profesor>ABC</profesor>
    </asignatura>

    <asignatura cod_asignatura="INF001">
      <nombre>Informática</nombre>
      <nivel>4º ESO</nivel>
      <departamento>Ciencia y Tecnología</departamento>
      <profesor>CLC</profesor>
    </asignatura>

  </asignaturas>

</colegio>
